create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
create table admin (id_admin integer not null auto_increment, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), primary key (id_admin)) engine=InnoDB;
create table client (idclient integer not null auto_increment, address varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), primary key (idclient)) engine=InnoDB;
create table demmande (iddemande integer not null auto_increment, etat varchar(255), idclient integer, idtableau integer, primary key (iddemande)) engine=InnoDB;
create table tableau (idtableau integer not null auto_increment, annne integer not null, artiste varchar(255), chemin varchar(255), description varchar(255), largeur double precision not null, longeur double precision not null, prix double precision not null, titre varchar(255), primary key (idtableau)) engine=InnoDB;
alter table demmande add constraint FKmb7q7kvwlsnvu4svmagdif2m foreign key (idclient) references client (idclient);
alter table demmande add constraint FKdudb2vq7nd24y33ch4n9hqqly foreign key (idtableau) references tableau (idtableau);
